include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    avoid_relative_lib_imports: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_build_context_synchronously: true
